name: slide_env
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - jupyter
  - matplotlib
  - openslide
  - openslide-python
  - pandas
  - bioconda::bftools
  - scikit-image
  - conda-forge::dask
  - certifi
  - conda-forge::zarr
  - conda-forge::parallel
